# Generated by Django 3.2.3 on 2021-05-23 04:03

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='media')),
                ('file_name', models.FileField(upload_to='', verbose_name=builtins.max)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
    ]
