# Generated by Django 3.2.3 on 2021-05-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210523_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='files',
            field=models.JSONField(default=list),
        ),
    ]
