# Generated by Django 3.2.3 on 2021-05-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_issue_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
    ]
