# Generated by Django 3.2.3 on 2021-05-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_file_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
